node1:
    hostname: 192.168.2.191
    username: admin
    password: HPinvent
node2:
    hostname: 192.168.2.193
    username: admin
    password: HPinvent
node3:
    hostname: 192.168.2.194
    username: admin
    password: HPinvent
docker1:
    hostname: 172.17.0.2:8004
    username: None
    password: None
docker2:
    hostname: 172.17.0.3:8004
    username: None
    password: None
docker3:
    hostname: 172.17.0.4:8004
    username: None
    password: None
docker4:
    hostname: 172.17.0.5:8004
    username: None
    password: None
docker5:
    hostname: 172.17.0.6:8004
    username: None
    password: None
docker6:
    hostname: 172.17.0.7:8004
    username: None
    password: None
docker7:
    hostname: 172.17.0.8:8004
    username: None
    password: None
docker8:
    hostname: 172.17.0.9:8004
    username: None
    password: None
docker9:
    hostname: 172.17.0.10:8004
    username: None
    password: None
docker10:
    hostname: 172.17.0.11:8004
    username: None
    password: None
docker11:
    hostname: 172.17.0.12:8004
    username: None
    password: None
docker12:
    hostname: 172.17.0.13:8004
    username: None
    password: None
docker13:
    hostname: 172.17.0.14:8004
    username: None
    password: None
docker14:
    hostname: 172.17.0.15:8004
    username: None
    password: None
docker15:
    hostname: 172.17.0.16:8004
    username: None
    password: None
docker16:
    hostname: 172.17.0.17:8004
    username: None
    password: None
docker17:
    hostname: 172.17.0.18:8004
    username: None
    password: None
docker18:
    hostname: 172.17.0.19:8004
    username: None
    password: None
docker19:
    hostname: 172.17.0.20:8004
    username: None
    password: None
docker20:
    hostname: 172.17.0.21:8004
    username: None
    password: None































