local:
    hostname: 192.168.2.192
    username: admin
    password: HPinvent
node2:
    hostname: 192.168.2.193
    username: admin
    password: HPinvent
node3:
    hostname: 192.168.2.194
    username: admin
    password: HPinvent

