node1:
  hostname: localhost
  username: NA
  password: NA
node2:
  hostname: 192.168.2.192
  username: admin
  password: HPinvent
node3:
  hostname: 192.168.2.194
  username: admin
  password: HPinvent  
docker1:
  hostname: 172.17.0.2:8004
  username: None
  password: None
