node1:
    hostname: 192.168.2.191
    username: admin
    password: HPinvent
node2:
    hostname: 192.168.2.193
    username: admin
    password: HPinvent
node3:
    hostname: 192.168.2.194
    username: admin
    password: HPinvent
docker1:
    hostname: 172.17.0.2:8004
    username: None
    password: None
docker2:
    hostname: 172.17.0.3:8004
    username: None
    password: None
docker3:
    hostname: 172.17.0.4:8004
    username: None
    password: None
docker4:
    hostname: 172.17.0.5:8004
    username: None
    password: None
docker5:
    hostname: 172.17.0.6:8004
    username: None
    password: None
docker6:
    hostname: 172.17.0.7:8004
    username: None
    password: None
docker7:
    hostname: 172.17.0.8:8004
    username: None
    password: None
docker8:
    hostname: 172.17.0.9:8004
    username: None
    password: None
docker9:
    hostname: 172.17.0.10:8004
    username: None
    password: None
docker10:
    hostname: 172.17.0.11:8004
    username: None
    password: None
docker11:
    hostname: 172.17.0.12:8004
    username: None
    password: None
docker12:
    hostname: 172.17.0.13:8004
    username: None
    password: None
docker13:
    hostname: 172.17.0.14:8004
    username: None
    password: None
docker14:
    hostname: 172.17.0.15:8004
    username: None
    password: None
docker15:
    hostname: 172.17.0.16:8004
    username: None
    password: None
docker16:
    hostname: 172.17.0.17:8004
    username: None
    password: None
docker17:
    hostname: 172.17.0.18:8004
    username: None
    password: None
docker18:
    hostname: 172.17.0.19:8004
    username: None
    password: None
docker19:
    hostname: 172.17.0.20:8004
    username: None
    password: None
docker20:
    hostname: 172.17.0.21:8004
    username: None
    password: None
docker21:
    hostname: 172.17.0.22:8004
    username: None
    password: None
docker22:
    hostname: 172.17.0.23:8004
    username: None
    password: None
docker23:
    hostname: 172.17.0.24:8004
    username: None
    password: None
docker24:
    hostname: 172.17.0.25:8004
    username: None
    password: None
docker25:
    hostname: 172.17.0.26:8004
    username: None
    password: None
docker26:
    hostname: 172.17.0.27:8004
    username: None
    password: None
docker27:
    hostname: 172.17.0.28:8004
    username: None
    password: None
docker28:
    hostname: 172.17.0.29:8004
    username: None
    password: None
docker29:
    hostname: 172.17.0.30:8004
    username: None
    password: None
docker30:
    hostname: 172.17.0.31:8004
    username: None
    password: None
docker31:
    hostname: 172.17.0.32:8004
    username: None
    password: None
docker32:
    hostname: 172.17.0.33:8004
    username: None
    password: None
docker33:
    hostname: 172.17.0.34:8004
    username: None
    password: None
docker34:
    hostname: 172.17.0.35:8004
    username: None
    password: None
docker35:
    hostname: 172.17.0.36:8004
    username: None
    password: None
docker36:
    hostname: 172.17.0.37:8004
    username: None
    password: None
docker37:
    hostname: 172.17.0.38:8004
    username: None
    password: None
docker38:
    hostname: 172.17.0.39:8004
    username: None
    password: None
docker39:
    hostname: 172.17.0.40:8004
    username: None
    password: None
docker40:
    hostname: 172.17.0.41:8004
    username: None
    password: None
docker41:
    hostname: 172.17.0.42:8004
    username: None
    password: None
docker42:
    hostname: 172.17.0.43:8004
    username: None
    password: None
docker43:
    hostname: 172.17.0.44:8004
    username: None
    password: None
docker44:
    hostname: 172.17.0.45:8004
    username: None
    password: None
docker45:
    hostname: 172.17.0.46:8004
    username: None
    password: None
docker46:
    hostname: 172.17.0.47:8004
    username: None
    password: None
docker47:
    hostname: 172.17.0.48:8004
    username: None
    password: None
docker48:
    hostname: 172.17.0.49:8004
    username: None
    password: None
docker49:
    hostname: 172.17.0.50:8004
    username: None
    password: None
docker50:
    hostname: 172.17.0.51:8004
    username: None
    password: None






























