#!/bin/sh
ROOT="${PWD}/../../"
export PATH=/root/PowerAPI-Redfish/bin:$PATH
export ROOT="${PWD}/../../"
export LD_LIBRARY_PATH="${ROOT}/lib:${LD_LIBRARY_PATH}"
export DYLD_LIBRARY_PATH="${ROOT}/lib:${DYLD_LIBRARY_PATH}"
export POWERAPI_CONFIG="${ROOT}/config/daemon_redfish.xml"
export POWERAPI_SERVER_PORT="15000"
export POWERAPI_SERVER="localhost"
export POWERAPI_DEBUG=0
export POWERAPI_ROOT=plat
