#!/bin/sh

ROOT="${PWD}/../.."
export POWERAPI_DEBUG=15
export POWERAPI_CONFIG="${ROOT}/config/daemon_redfish.xml"
export CONFIG="${ROOT}/config/daemon_redfish.xml"
export POWERAPI_ROOT="plat.cab0"

./pwrdaemon \
--rtr.clientPort=15000 \
--rtr.serverPort=15001 \
--rtr.routerType=tree \
--rtr.routerId=0 \
--rtr.routeTable=routeTable.txt \
--srvr.rtrHost=192.168.2.91 \
--srvr.rtrPort=15001 \
--srvr.pwrApiConfig=$POWERAPI_CONFIG \
--srvr.pwrApiRoot=plat.cab0

