#!/bin/sh


export POWERAPI_DEBUG=0

CONFIG=$1

pwrdaemon \
--rtr.clientPort=15000 \
--rtr.serverPort=15001 \
--rtr.routerType=tree \
--rtr.routerId=0 \
--rtr.routeTable=routeTable.txt \
--srvr.rtrHost=localhost \
--srvr.name=cab0 \
--srvr.rtrPort=15001 \
--srvr.pwrApiConfig=$CONFIG \
--srvr.pwrApiRoot=plat.cab0 \
--srvr.pwrApiServer=localhost \
--srvr.pwrApiServerPort=15000 \
--srvr0.name=chassis1 \
--srvr0.rtrHost=localhost \
--srvr0.rtrPort=15001 \
--srvr0.pwrApiConfig=$CONFIG \
--srvr0.pwrApiRoot=plat.cab0.chassis1 \
--srvr1.name=chassis2 \
--srvr1.rtrHost=localhost \
--srvr1.rtrPort=15001 \
--srvr1.pwrApiConfig=$CONFIG \
--srvr1.pwrApiRoot=plat.cab0.chassis2

