#!/bin/sh
ROOT="${PWD}/../../../../"
DAEMON="${PWD}/../../"
export PATH="${ROOT}/opt/PowerAPI/bin:$PATH}"
export ROOT="${PWD}/../../../../"
export LD_LIBRARY_PATH="${ROOT}/opt/PowerAPI/lib:${LD_LIBRARY_PATH}"
export DYLD_LIBRARY_PATH="${ROOT}/opt/PowerAPI/lib:${DYLD_LIBRARY_PATH}"
export POWERAPI_CONFIG="${DAEMON}/config/daemon_redfish.xml"
export POWERAPI_SERVER_PORT="15000"
export POWERAPI_SERVER="localhost"
export POWERAPI_DEBUG=0
export POWERAPI_ROOT=plat
