#!/bin/sh
ROOT="${PWD}/../.."
export POWERAPI_DEBUG=30
export LD_LIBRARY_PATH="${ROOT}/lib:${LD_LIBRARY_PATH}"
export DYLD_LIBRARY_PATH="${ROOT}/lib:${DYLD_LIBRARY_PATH}"
export POWERAPI_CONFIG="${ROOT}/config/daemon_redfish.xml"
export CONFIG="${ROOT}/config/myconfig_redfish.xml"
export POWERAPI_ROOT="plat.cab0.node1"
./pwrdaemon \
--srvr.rtrHost=192.168.2.91 \
--srvr.rtrPort=15001 \
--srvr.pwrApiConfig=$POWERAPI_CONFIG \
--srvr.pwrApiRoot=plat.cab0.node1

