#!/bin/sh

export POWERAPI_DEBUG=0

CONFIG=/root/daemon/dummySystem.xml

pwrdaemon \
--srvr.rtrHost=localhost \
--srvr.rtrPort=15001 \
--srvr.pwrApiConfig=$CONFIG \
--srvr.pwrApiRoot=plat.cab0.chassis1.docker1
