#!/bin/sh

ROOT="${PWD}/../.."
export POWERAPI_DEBUG=15
export POWERAPI_CONFIG="/root/PowerAPI_Working_Code/PowerAPI-Redfish/config/daemon_redfish.xml"
export CONFIG="/root/PowerAPI_Working_Code/PowerAPI-Redfish/config/daemon_redfish.xml"
export POWERAPI_ROOT="plat.cab0"

/root/PowerAPI_Working_Code/pwrapi-ref/tools/pwrdaemon/./pwrdaemon \
--rtr.clientPort=15000 \
--rtr.serverPort=15001 \
--rtr.routerType=tree \
--rtr.routerId=0 \
--rtr.routeTable=routeTable.txt \
--srvr.rtrHost=192.168.2.92 \
--srvr.rtrPort=15001 \
--srvr.pwrApiConfig=$POWERAPI_CONFIG \
--srvr.pwrApiRoot=plat.cab0

