nodename: node0,local
node0: 
    iloIP: 192.168.2.191
    username: admin
    password: HPinvent
local:
    iloIP: 192.168.2.192
    username: admin
    password: HPinvent
node2:
    iloIP: 192.168.2.193
    username: admin
    password: HPinvent
node3:
    iloIP: 192.168.2.194
    username: admin
    password: HPinvent

