chassis:
    AvgPower:
        URL: /redfish/v1/Chassis/1/Power/FastPowerMeter
        get: Average
        script: Ilo_Chassis_Avg_Power
    MaxPower:
        URL: /redfish/v1/Chassis/1/Power/FastPowerMeter/
        get: Maximum
        script: Ilo_Chassis_Max_Power
    MinPower:
        URL: /redfish/v1/Chassis/1/Power/FastPowerMeter/
        get: Minimum
        script: Ilo_Chassis_Min_Power
    Power:
        URL: /redfish/v1/Chassis/1/Power
        get: PowerConsumedWatts
        script: Ilo_Chassis_Power
cpu:
    Voltage:
        URL: /redfish/v1/Systems/1/Processors/1/
        get: VoltageVoltsX10
        script: Ilo_CPU_Voltage
    Temperature:
        URL: /redfish/v1/Chassis/1/Thermal/
        get: CurrentReading
        script: Ilo_CPU_Temperature
    Frequency:
        URL: /redfish/v1/Systems/1/Processors/1/
        get: MaxSpeedMHz
        script: Ilo_CPU_Freq
memory:
    Voltage:
        URL: /redfish/v1/Systems/1/Memory/proc1dimm8
        get: MinimumVoltageVoltsX10
        script: Ilo_Memory_Voltage
    Temperature:
        URL: /redfish/v1/Chassis/1/Thermal/
        get: CurrentReading
        script: Ilo_Memory_Temperature
    Frequency:
        URL: /redfish/v1/Systems/1/Memory/proc1dimm8
        get: MaximumFrequencyMHz
        script: Ilo_Memory_Frequency


