Chassis:
    Power:
        URL: /redfish/v1/Chassis/chassis$/Power
        get: PowerConsumedWatts
        script: Ilo_Chassis_Power
    AvgPower:
        URL: /rest/v1/Chassis/chassis$/Power/FastPowerMeter
        get: Average
        script: Ilo_Chassis_Avg_Power
    MaxPower:
        URL: /redfish/v1/Chassis/chassis$/Power/FastPowerMeter/
        get: Maximum
        script: Ilo_Chassis_Max_Power
    MinPower:
        URL: /redfish/v1/Chassis/chassis$/Power/FastPowerMeter/
        get: Minimum
        script: Ilo_Chassis_Min_Power
CPU:
    Voltage:
        URL: /redfish/v1/Systems/chassis$/Processors/cpu$/
        get: VoltageVoltsX10
        script: Ilo_CPU_Voltage
    Temperature:
        URL: /redfish/v1/Chassis/chassis$/Thermal/
        get: CurrentReading
        script: Current_Reading
    Frequency:
        URL: /redfish/v1/Systems/chassis$/Processors/cpu$/
        get: MaxSpeedMHz
        script: Ilo_CPU_Freq
Memory:
    Voltage:
        URL: /redfish/v1/Systems/system$/Memory/
        get: MinimumVoltageVoltsX10
        script: Ilo_Memory_Voltage
    Temperature:
        URL: /redfish/v1/Chassis/system$/Thermal/
        get: CurrentReading
        script: Current_Reading
    Frequency:
        URL: /redfish/v1/Systems/system$/Memory/
        get: MaximumFrequencyMHz
        script: Ilo_Memory_Freq


