chassis:
    AvgPower:
      get:
        URL: /redfish/v1/Chassis/{chassis}/Power/FastPowerMeter
        attribute: Average
        script: Ilo_Generic
    MaxPower:
      get:
        URL: /redfish/v1/Chassis/{chassis}/Power/FastPowerMeter
        attribute: Maximum
        script: Ilo_Generic
    MinPower:
      get:
        URL: /redfish/v1/Chassis/{chassis}/Power/FastPowerMeter
        attribute: Minimum
        script: Ilo_Generic
    Power:
      get:
        URL: /redfish/v1/Chassis/{chassis}/Power/
        attribute: PowerConsumedWatts
        script: Ilo_Generic
cpu:
    Voltage:
      get:
        URL: /redfish/v1/Systems/{system}/Processors/{cpu}
        attribute: VoltageVoltsX10
        script: Ilo_CPU_Voltage
    Temp:
      get:
        URL: /redfish/v1/Chassis/{chassis}/Thermal/
        attribute: CurrentReading
        script: Ilo_CPU_Temperature
    Frequency:
      get:
        URL: /redfish/v1/Systems/{system}/Processors/{cpu}/
        attribute: MaxSpeedMHz
        script: Ilo_Generic
memory:
    Voltage:
      get:
        URL: /redfish/v1/Systems/{system}/Memory/proc{cpu}dimm{memory}
        attribute: MinimumVoltageVoltsX10
        script: Ilo_Generic
    Temp:
      get:
        URL: /redfish/v1/Chassis/{chassis}/Thermal/
        attribute: CurrentReading
        script: Ilo_Memory_Temperature
    Frequency:
      get:
        URL: /redfish/v1/Systems/{system}/Memory/proc{cpu}dimm{memory}
        attribute: MaximumFrequencyMHz
        script: Ilo_Generic
system:
    C-State:
      get:
        URL: /redfish/v1/Systems/{system}/bios/
        attribute: MinProcIdlePower
        script: Ilo_System_CState       
      set:
        URL: /redfish/v1/Systems/{system}/bios/Settings
        attribute: MinProcIdlePower
        script: Ilo_System_CState
    Power:
      set:
        URL: /redfish/v1/Systems/{system}/
        attribute: ResetType
        script: Ilo_System_Reset
    PowerProfile:
      get:
        URL: /redfish/v1/Systems/{system}/bios/
        attribute: PowerProfile
        script: Ilo_System_PowerProfile       
      set:
        URL: /redfish/v1/Systems/{system}/bios/Settings
        attribute: PowerProfile
        script: Ilo_System_PowerProfile
    CPackageState:
      get:
        URL: /redfish/v1/Systems/{system}/bios/
        attribute: MinProcIdlePkgState
        script: Ilo_System_CPackageState       
      set:
        URL: /redfish/v1/Systems/{system}/bios/Settings
        attribute: MinProcIdlePkgState
        script: Ilo_System_CPackageState
